### ISSUE TITLE
Interpolation in queries & strange behaviour with ' in place of "

### ISSUE THREAD

**Issue by KaruroChori** [Rolands-Laucis/Socio#16]
At the moment, it seems like queries in this form are failing:
>await sc.Query(
              "INSERT INTO users:ch (name, num) VALUES(:name, :num);--socio",
              {name: "Bob", num: 42, ch: "001a2ff"}
            );

The interpolation of a table/view name is particularly useful when targetting custom views based on a source table, to split the update triggers and avoid propagating changes globally. 

Also it seems like writing 'Bob' or "Bob" is not the same, as the first will fail, resulting in:
_Error: the cipher text does not contain exactly 3 space seperated parts, therefor is invalid. [#cipher-text-invalid-format]_

**Comment by Rolands-Laucis** [comment]
I dont understand what you mean with the first paragraph, but i think this isnt a Socio related issue, as Socio doesnt handle constructing queries or modifying them. Just parsing them in some cases.

If you are using Sequelize's raw query function, then [see this documentation](https://sequelize.org/docs/v6/core-concepts/raw-queries/#replacements) about how the replacements work. In the demos, the params object givent to SocioClient.Query('...', params) is literally given to sequelize.query('...', {replacements:params}). Seems like sequelize seems to have trouble parsing that replacement syntax. 

The given query code snippet produces `SequelizeDatabaseError: SQLITE_ERROR: near ":ch": syntax error` for me in the basic demo env. Perhaps a replacement near a table name is invalid?

If :ch is used by itself without the 'users' part, then it gives `SequelizeDatabaseError: SQLITE_ERROR: no such table: 001a2ff`, which is logically correct.

And if `users :ch` is used with a space: `SequelizeDatabaseError: SQLITE_ERROR: near "'001a2ff'": syntax error`, which is again correct.

However, reading the documentation thoroughly myself, I realize that an array can also be passed instead of an object, so i will be fixing that expected type in Socio some time later.

As for the last paragraph - i cannot reproduce. Both 'Bob' and "Bob" should be work identically, since it will be JSON.stringified through the network and arrive to the backend as "Bob" in both cases, as per the JSON spec. Still, both are afaik identical notations for a string literal in JS, so it wouldnt matter even if the quotes were different.

In addition, the [#cipher-text-invalid-format] error would only pop up when you are using SocioSecurity and the queries are expected to be received encrypted. SocioServer has also flags for disabling decipher completely, just for SQL or just for props (as they can also be encrypted).

**Comment by KaruroChori** [comment]
As for the second issue, I am just basing it on your svelte example:
Line 134 of +page.svelte

```
            await sc.Query(
              "INSERT INTO users (name, num) VALUES(:name, :num);--socio",
              {name: "Bob", num: 42}
            );
```

or 

```
            await sc.Query(
              "INSERT INTO users (name, num) VALUES(:name, :num);--socio",
              {name: 'Bob', num: 42}
            );
```

The first one is working as expected, the second one result in the error I described earlier. Can you replicate it this way?
It makes no sense to me as well.
I just assumed some of the automagical regex of the vite plugin were not working there, but I failed to identify the source of the problem.

I can upload the affected code in a fork if it helps.

**Comment by KaruroChori** [comment]
As for the first point, thank you for the reply.
> Perhaps a replacement near a table name is invalid?
It seems so. But the second option is as good and it would work, so I will stick to that :).

**Comment by KaruroChori** [comment]
I will check in the weekend if I can find any reasonable solution.

I really mean string interpolation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#string_interpolation
It is a semantic extension of the usual concept of interpolation in math.
The operation of interpolating substrings into a pattern is often referred as such.

**Comment by KaruroChori** [comment]
The easiest way I found is to use prettier to strip comments.
https://stackoverflow.com/questions/37051797/remove-comments-from-string-with-javascript-using-javascript
Also, it detects strings directly, so there is no need to use additional regex for that. You can work on the AST of the original file and integrate any side-effect desired.

Other solutions based on regex you might find like this https://stackoverflow.com/questions/37051797/remove-comments-from-string-with-javascript-using-javascript
will not work, because comments inside strings are also detected.

**Comment by Rolands-Laucis** [comment]
Using an engine like prettier for such a problem seems overkill. And the AST parsing idea would make the parsing less general, i.e. only certain files would be parsable by the parser, and only those then usable by Socios Vite plugin. I'd like to stick to regex, as then the file type and content is irrelevant, so long as it is plaintext.

I've come up with a longer and more complex regex pattern, by combining the old 2 and fixing a problem. 

> /(["'`])(?:(?!\1)(?:.|\n))*?(?<marker>--socio(?:-\w+?)*)(?:[;\s]+)?\1/ig

^idk how to escape githubs markdown, so this will look wrong.

[Regex101 demo](https://regex101.com/r/6qmCNp/1). For JS this seems to work on the full-stack demo +page.svelte whole file. newlines and tabs etc. Matches only the socio strings and captures the semantic groups correctly. I will think about this for a while longer, and if you also dont find anything wrong with this, then i will eventually replace the existing parsing logic to just use this instead. Should also give a performance boost for the vite plugin as well i guess.

Turns out [Backreferences](https://www.regular-expressions.info/backref.html) dont work in `[^\1]` to match anything except the first capture, i.e. the starting quote symbol. Which i had in the old regex. They only mention this at the end of the page :D great
> Backreferences, too, cannot be used inside a character class. The \1 in a regex like (a)[\1b] is either an error or a needlessly escaped literal 1. In [JavaScript](https://www.regular-expressions.info/javascript.html) it’s an [octal escape](https://www.regular-expressions.info/nonprint.html#octal).

So instead i use the (?:(?!\1)(?:.|\n))*? negative lookahead (?!\1)

Also i was not aware of the "string interpolation" term 👌

**Comment by KaruroChori** [comment]
It seems fine.
I was able to come up with few examples where it fails or matches more than what would be reasonable, but they are very much intentional & artificial.

To be honest I think an approach based on tagged templates would be better, as it is semantically supported by js/ts.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Basically, writing socio queries would be like socio`CREATE TABLE ${name} ....`

For reference, this concept applied to sequelize: https://dev.to/newbie012/please-dont-manually-parameterize-your-sql-queries-3m7k

**Comment by Rolands-Laucis** [comment]
That is actually brilliant. Where were you like 3 months ago :D Before the SocioSecurity class, i had been thinking about ways to have a marker somewhere at the front of the string rather than at the end, like putting a $ or # , but that would be fine in either JS or SQL syntax.
I didnt know JS had such a tagged template feature. That is really powerful.

So i guess, this will be used instead. The socio template tag will just be a dummy function. The regex will be much simpler to just find strings with that template tag and replace with encrypted string that doesnt even need the tag anymore. And perhaps i can create an actual SQL formatter function on the backend for devs that use sequelize.

The drawbacks i see here are that socio strings must always be template string literals. And they need the tag, which has to be imported from the lib or your own dummy function defined somewhere, just so IDE's dont complain. Also then the auth and perm markers will be handled slightly different. Since having an ending --socio-auth would be repetitive. There are a few different ways to handle them now tho, so thats fine.
